### ISSUE TITLE
Explanation on checkGradient

### ISSUE THREAD

**Issue by jinz2014** [lephong/lstm-rnn#2]
I am learning, but I don't understand the function shown below. Could you please explain it in detail ?

Thank you,

void AbstractNN::checkGradient(Treebank* tb) {
	real epsilon = 1e-4;
    AbstractParam** grad = new AbstractParam*[nThreads];
    for (int i = 0; i < nThreads; i++)
        grad[i] = createGrad();
	void** output = computeCostAndGrad(tb, 0, tb->size()-1, grad);
	delete[] output;

	vector<real> gradV;
	vector<real> numGradV;
    AbstractParam** otherGrad = new AbstractParam*[nThreads];
    for (int i = 0; i < nThreads; i++)
        otherGrad[i] = createGrad();

	for (int i = 0; i < params->weights.size(); i++) {
		Matrix* W = params->weights[i];
		for (int r = 0; r < W->rows; r++)
			for (int c = 0; c < W->cols; c++) {
				gradV.push_back(grad[0]->weights[i]->get(r,c));

				// plus
				W->put(r, c, W->get(r,c)+epsilon);
				output = computeCostAndGrad(tb, 0, tb->size()-1, otherGrad);
				real pluscost = *(real*)output[0];
				delete[] output;

				// minus
				W->put(r, c, W->get(r,c)-2*epsilon);
				output = computeCostAndGrad(tb, 0, tb->size()-1, otherGrad);
				real minuscost = *(real*)output[0];
				delete[] output;

				W->put(r, c, W->get(r,c)+epsilon);

				numGradV.push_back((pluscost - minuscost) / (2*epsilon));
				real diff = abs(numGradV.back() - gradV.back());
				if (diff > 0 && abs(gradV.back()) < 1e-7)
					cout << diff << " " << i << " " << r << " " << c << " : " << numGradV.back() << " " << gradV.back() << endl;
				if (diff > 5e-9)
					cout << diff << " " << i << " " << r << " " << c << " : " << numGradV.back() << " " << gradV.back() << endl;
			}
	}

	Matrix* X = new Matrix((int)gradV.size(), &gradV[0]);
	Matrix* Y = new Matrix((int)numGradV.size(), &numGradV[0]);
	real diff = Matrix::nrm2(X->add(-1, Y)) / Matrix::nrm2(X->add(Y));
	cout << diff << endl;
    cout << "should be < 1e-9" << endl;

    for (int i = 0; i < nThreads; i++) {
        delete grad[i];
        delete otherGrad[i];
    }
    delete[] grad;
    delete[] otherGrad;
    delete X;
    delete Y;
}

**Comment by lephong** [comment]
this is for checking whether the gradients are computed correctly or not (before the era of Tensor Flow, Pytorch, ...). For more details, you can read http://deeplearning.stanford.edu/tutorial/supervised/DebuggingGradientChecking/
