### ISSUE TITLE
Keras model 

### ISSUE THREAD

**Issue by jinz2014** [lephong/lstm-rnn#3]
I wonder if you wrote a model using, for example, Keras that is equivalent to your C++ implementation.  It is very interesting to look at the model written using frameworks such as Tensorflow. Would it be possible that you could have such implementation in your repository ?

Thanks

**Comment by lephong** [comment]
Unfortunately I don't have any other implementations. One thing you can look at is tree-lstm implementations (there are plenty). Tree-lstm and my model are pretty similar.
